"""Validate every Napoleon record against every Napoleon schema and write napoleon/MATRIX.md.

Usage (from the repo root):
    .venv/bin/python napoleon/matrix.py

Each schema is used with its tree_root class and closed validation, which is what
linkml-validate -s SCHEMA -C CLASS FILE does. Rows are data files, columns are schemas.
"""

from pathlib import Path

import yaml
from linkml.validator import Validator
from linkml.validator.plugins import JsonschemaValidationPlugin
from linkml_runtime.utils.schemaview import SchemaView

ROOT = Path(__file__).resolve().parent
REPO = "https://github.com/turbomam/linkml-missing-value-patterns/blob/slides-obi-2026-09-14/napoleon"
SCHEMAS = ["strict", "union", "one_of", "value_object", "reason_column", "side_report", "not_applicable"]


def root_class(path: Path) -> str:
    sv = SchemaView(str(path))
    return next(c.name for c in sv.all_classes().values() if c.tree_root)


def main() -> None:
    validators = {}
    for s in SCHEMAS:
        path = ROOT / "schema" / f"{s}.yaml"
        validators[s] = (Validator(str(path), validation_plugins=[JsonschemaValidationPlugin(closed=True)]), root_class(path))
    files = sorted(f for f in (ROOT / "data").glob("*/*.yaml") if f.name != "all_valid_records.yaml")
    header = "| data file | " + " | ".join(f"[{s}]({REPO}/schema/{s}.yaml)" for s in SCHEMAS) + " |"
    lines = [
        "# Every Napoleon record against every Napoleon schema",
        "",
        "Generated by `just linkml-matrix`. pass = no errors; FAIL = at least one error. Each cell is what",
        "`linkml-validate -s napoleon/schema/SCHEMA.yaml -C ROOTCLASS FILE` reports, where ROOTCLASS is the",
        "schema's tree_root: " + ", ".join(f"{s} `{validators[s][1]}`" for s in SCHEMAS) + ".",
        "The file name says which schema it was written for (`data/SCHEMA/valid_*` or `invalid_*`).",
        "",
        header,
        "|---|" + "---|" * len(SCHEMAS),
    ]
    for f in files:
        instance = yaml.safe_load(f.read_text())
        cells = []
        for s in SCHEMAS:
            v, cls = validators[s]
            ok = not any(True for _ in v.iter_results(instance, cls))
            own = f.parent.name == s
            cell = "pass" if ok else "FAIL"
            cells.append(f"**{cell}**" if own else cell)
        rel = f"{f.parent.name}/{f.name}"
        lines.append(f"| [{rel}]({REPO}/data/{rel}) | " + " | ".join(cells) + " |")
    lines += ["", "Bold cells are the schema the file was written for."]
    (ROOT / "MATRIX.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines[7:]))


if __name__ == "__main__":
    main()
